server:
  port: 10010
spring:
  application:
    name: springcloud-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  #prefix: /api # 路由路径前缀
  routes:
      user-service: /userService/** # 商品微服务的映射路径
      info-service: /infoService/** # 商品微服务的映射路径
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
