server:
  port: 8083
spring:
  application:
    name: info-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
feign:
  #熔断器配置
  hystrix:
    #开启熔断器
    enabled: true